### ISSUE TITLE
Create only one PR?

### ISSUE THREAD

**Issue by mazilu88** [wadackel/files-sync-action#213]
Is there a way to create a single PR per repo? I am using it like this, and it creates two separate PRs

```yaml
patterns:
  - files:
      - from: files/CODEOWNERS
        to: .github/CODEOWNERS
    repositories:
      - owner/repo

  - files:
      - from: workflows/integration-tests.yaml
        to: .github/workflows/integration-tests.yaml
    repositories:
      - owner/repo
```

**Comment by mazilu88** [comment]
Also, it would be nice if you could use templates in the `to` sections 

```
  - files:
      - from: files/charts
        to: charts/<%- repository %>/
    repositories:
      - owner/repo
```
