### ISSUE TITLE
Not syncing files with dot?

### ISSUE THREAD

**Issue by mazilu88** [wadackel/files-sync-action#215]
I am trying to sync a folder with multiple files. The file starting with dot is not synced

file structure
```yaml
files
 - root
    - .dockerignore
    - Dockerfile
```

files-sync-config.yaml
```yaml
  - files:
      - from: files/root
        to: ./
    repositories:
      - repo/owner
```
